name: wrinkler
channels:
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.19.*
  - matplotlib=3.3.*
  - pandas=1.2.*
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.0
  - pip:
    - pytorch-lightning==1.1.4
    - segmentation_models.pytorch==0.1.3
    - p_tqdm==1.3.3
    - albumentations==0.5.2
    - flake8==3.8.4
    - yapf==0.30.0
